# install.packages("lpSolve")
library(lpSolve)
objective <- c(3,2)
constraints <- matrix(c(1,1, 1,0, 0,1), nrow=3, byrow=TRUE)
direction <- c(">=",">=",">=")
rhs <- c(4,1,1)
res <- lp("min", objective, constraints, direction, rhs)
print(res$solution)
print(res$objval)
