# install.packages("nnet")
library(nnet)
set.seed(42)
x <- matrix(rnorm(1000), ncol=5)
y <- 2*x[,1] - x[,2] + 0.5*x[,3] + rnorm(nrow(x), sd=.1)
df <- data.frame(y=y, x)
model <- nnet(y ~ ., data=df, size=8, linout=TRUE, maxit=500, trace=FALSE)
pred <- predict(model, df)
print(sqrt(mean((pred-y)^2)))
